### ISSUE TITLE
Bot replies to itself when it says its own name

### ISSUE THREAD

**Issue by Garry-Marshall** [mercm8/chat-llama-discord-bot#3]
Probably in this part of the code:

>         if (self.only_speak_when_spoken_to and client.user.mentioned_in(message) \
>                    or any(word in message.content.lower() for word in client.user.display_name.lower().split())) \
>                or (self.in_active_conversation(message.author.id) and message.channel.id == self.main_channel):
>            """ If bot is set to only speak when spoken to and someone uses its name
>                or if is in an active conversation with the user in the main channel, we reply. 
>                This is a messy one. """

**Comment by Garry-Marshall** [comment]
I tried adding
>and message.author != client.user:

but that doesn't change anything.

From time to time, it gets stuck in a loop and repeats itself over and over again.

**Comment by mercm8** [comment]
Ah, I havent noticed this, thanks for pointing it out. Guess I have to stir the spaghetti some more.. Pretty sure there already is a "do not reply to yourself" logic in the behavior that should make it abort immediately, but it's probably overridden by some other spaghetti at this point.

**Comment by Garry-Marshall** [comment]
That seems to have fixed it.
