### ISSUE TITLE
emoji detection doesn't work

### ISSUE THREAD

**Issue by Garry-Marshall** [mercm8/chat-llama-discord-bot#5]
I used the text-clean package to filter out emojis.
There's probably more elegant solutions, maybe there's a built in function in the Discord api you could use.

>from cleantext import clean
  
>      if self.ignore_parenthesis and \
>            (message.content.startswith('(') and message.content.endswith(')') \
>            or \
>            #(message.content.startswith(':') and message.content.endswith(':'))):
>            clean(message.content, no_emoji=True) == ""):
>            """ if someone is simply using an :emoji: or (speaking like this) """
>            return False

**Comment by mercm8** [comment]
yep, looks like it should be <:emoji:> not :emoji:. 

There's a built in one too, but gonna change it to this for now (and totally fix it later for sure)
