### ISSUE TITLE
Update to Ooba-Webui borked smth, I think.

### ISSUE THREAD

**Issue by MuXodious** [mercm8/chat-llama-discord-bot#6]
Steps:
1. "git pull" on webui
2. run the bot as usual
3. call the bots name and type anything
4. see following and no reply from the bot

![Screenshot from 2023-05-15 22-19-21](https://github.com/mercm8/chat-llama-discord-bot/assets/64381665/242ba1fa-bce2-46ab-a992-f6c62e36c3f8)

**Comment by TheLounger** [comment]
You can try this, it fixed that error for me.

https://github.com/TheLounger/chat-llama-discord-bot/commit/a8d98515a0ca9fef45b12f4ee3f905315f75661a

**Comment by mercm8** [comment]
fixed this now, thanks for the help Lounger
