### ISSUE TITLE
Making extentions work with the bot.

### ISSUE THREAD

**Issue by MuXodious** [mercm8/chat-llama-discord-bot#7]
Is it possible to make extentions like EdgeGPT work with the bot? So far from my observations bot.py doesn't load any extentions even when specified as arguments. It would be nice to have things like "superbooga" and "EdgeGPT" working.

**Comment by mercm8** [comment]
I honestly have no idea, I'm not using extensions myself. I'll look into it but can't really make any promises. A guy on discord said I could just throw in `extensions_module.load_extensions()` and that should take care of it. We'll see.

**Comment by MuXodious** [comment]
Hey! Thank you for your hard work. I have been looking in to the matter. I must say that I'm just someone who can read code not write before I continue. I managed to get the extensions load, but I'm not sure if they're working as they're intended to be. Here:

![image](https://github.com/mercm8/chat-llama-discord-bot/assets/64381665/33949ea8-bcef-4386-a934-f3b03316027a)

Here's the changes to get this result: 

https://github.com/MuXodious/chat-llama-discord-bot/commit/b68fa569748ba9928eb65d6724abf40c3957113d

**Comment by mercm8** [comment]
Looks promising! I'll look into this (and extensions in general) over the weekend. 

Would be kinda cool to get the tts extensions working over voice channels for example.

**Comment by MuXodious** [comment]
No rush ^^. Again, thank you for your time. Indeed, It would be nice to enable STT and TTS plugins then invite the bot to a voice channel, where we can have a conversation or use it as a voice assistant/voice-activated assistant. Let me know if you need someone to test something or have anything that I can help with. Perhaps, I'll try loading STT, TTS, and some other extensions and see what happens in the mean time. I can open a pull request too, If you want to continue from there instead of this issue.

So far I made some changes to EdgeGPT's script.py and extension does work, but errors out as following when called, might be an incompatibility with the bot but leaving here for reference. 

```
custom_generate_chat_prompt.<locals>.EdgeGPT' was never awaited
  await self.on_error(event_name, *args, **kwargs)
```

One last thing, I identified a bug where bot when launched without A1111, spams the following excerpt to the chat non-stop until it's turned off.

`Launch Automatic1111 with the --api commandline argument\nRead more [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)`


![bot](https://github.com/mercm8/chat-llama-discord-bot/assets/64381665/7080204f-c7d3-4aa6-aeba-ab0c38348e5e)

**Comment by mercm8** [comment]
yeah that was a nasty one, just discovered it myself, should be fixed now though

**Comment by mercm8** [comment]
also I think discord api doesnt allow for bots to record audio from voice channels, unfortunately
